### Get all failed
GET http://localhost:4000/member

### Get all
GET http://localhost:4000/api/members

### Get by id
GET http://localhost:4000/api/members/f15410b3-1ba1-4078-a004-5359041f6d53

### Get by name
GET http://localhost:4000/api/members/search?name=Zeus

### Get by status
GET http://localhost:4000/api/members/search?status=Active

### Get by joinedDate
GET http://localhost:4000/api/members/search?joinedDate=2021-07-26

### Get by name and status
GET http://localhost:4000/api/members/search?name=Lightning Revenant&status=Active

### Create Zeus
POST http://localhost:4000/api/members
Content-Type: application/json

{ 
	"name": "Zeus",
	"status": "Active",
	"joinedDate": "2021-07-25"
}

### Create Invalid Status
POST http://localhost:4000/api/members
Content-Type: application/json

{ 
	"name": "Storm Spirit",
	"status": "Actively",
	"joinedDate": "2021-07-27"
}

### Update - Should update Lucario
PUT http://localhost:4000/api/members
Content-Type: application/json

{
	"id": "f15410b3-1ba1-4078-a004-5359041f6d53",
	"name": "Lightning Revenant",
	"status": "Active",
	"joinedDate": "2021-01-26"
}

### Delete
DELETE http://localhost:4000/api/members/f15410b3-1ba1-4078-a004-5359041f6d53

